[project]
name = "memory-module"
version = "0.0.0"
description = "Memory module for creating intelligent agents within Microsoft Teams"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.20.0",
    "instructor>=1.6.4",
    "pydantic>=2.10.1",
    "python-dotenv>=1.0.1",
    "numpy",
    "litellm",
    "sqlite-vec>=0.1.6",
]
