[project]
name = "memory_module"
version = "0.1.0"
description = "Memory module for creating intelligent agents within Microsoft Teams"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.20.0",
    "instructor>=1.6.4",
    "pydantic>=2.10.1",
    "python-dotenv>=1.0.1",
    "numpy",
    "sqlite-vec>=0.1.6",
    "litellm==1.54.1",
    "botbuilder>=0.0.1",
]

[dependency-groups]
dev = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["memory_module"]