[project]
name = "customer-service-agent-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["memory-module", "dotenv", "aiohttp", "teams-ai", "botbuilder"]