name: "Build, Lint & Test"

on:
  pull_request:
    branches: ["**"]
    paths:
      - packages/memory_module/**
  push:
    branches: ["**"]
    paths:
      - packages/memory_module/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-lint-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: read
      checks: write
      pull-requests: write

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      # TODO: Re-enable once repo goes public
      # - name: Harden Runner
      #   uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      #   with:
      #     egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh -s -- --version 0.1.24

      - name: Install dependencies
        run: |
          uv sync

      - name: Lint (Ruff)
        uses: astral-sh/ruff-action@d0a0e814ec17e92d33be7d24dd922b479f1bcd38 # v1.1.1
        with:
          args: check

      - name: Format (Ruff)
        uses: astral-sh/ruff-action@d0a0e814ec17e92d33be7d24dd922b479f1bcd38 # v1.1.1
        with:
          args: "format"

      - name: Type Check (MyPy)
        run: |
          source .venv/bin/activate
          mypy

      - name: Run tests
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          AZURE_OPENAI_EMBEDDING_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT }}
          AZURE_OPENAI_API_BASE: ${{ secrets.AZURE_OPENAI_API_BASE }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
        run: |
          source .venv/bin/activate
          pytest tests/ -v
